### ISSUE TITLE
✘ No value provided for input HTTP label: Bucket. ✘ Cannot read property 'BucketName' of undefined

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [nessjs/ness#114]
me@pc /c/localhost/serverless-aws-next (main)
$ npx ness deploy
Need to install the following packages:
  ness
Ok to proceed? (y)
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: acorn@7.4.1
npm WARN node_modules/acorn
npm WARN   acorn@"^7.4.1" from @vercel/nft@0.9.6
npm WARN   node_modules/@vercel/nft
npm WARN     @vercel/nft@"^0.9.3" from @sls-next/lambda-at-edge@1.8.0-alpha.31
npm WARN     node_modules/@sls-next/lambda-at-edge
npm WARN   1 more (acorn-class-fields)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer acorn@"^6.0.1" from acorn-export-ns-from@0.1.0
npm WARN node_modules/acorn-export-ns-from
npm WARN   acorn-export-ns-from@"^0.1.0" from @vercel/nft@0.9.6
npm WARN   node_modules/@vercel/nft
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated acorn-export-ns-from@0.1.0: acorn>=7.2 supports export-ns-from
npm WARN deprecated acorn-import-meta@1.1.0: acorn>=7.2 supports import-meta
npm WARN deprecated acorn-numeric-separator@0.3.6: acorn>=7.4 supports numeric separators
npm WARN deprecated node-pre-gyp@0.13.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scope
d package will recieve updates in the future
npm WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0

✔ Validating AWS credentials (Account #805908571649)
✔ Updating .gitignore to ignore .ness directory
✘ No value provided for input HTTP label: Bucket.
✘ Cannot read property 'BucketName' of undefined

� Site successfully deployed:

**Comment by adamelmore** [comment]
Thanks for reporting! Do you mind to share the following?

• OS version
• Node version
• Repo for reproducing

**Comment by MaxmaxmaximusAWS** [comment]
@adamelmore sorry, I'm not so interested in a non-working project to spend at least a second to collect this information), most likely you will simply die into oblivion as another startup ^ __ ^
