### ISSUE TITLE
Ness doesn't seem to pickup AWS credentials

### ISSUE THREAD

**Issue by rushi** [nessjs/ness#156]
Ness can't seem to pick up the AWS credentials that are already configured in `~/.aws/credentials` The credentials are correct since I verified it by using `aws` on my terminal. My user is an IAM user with full privileges.

```bash
○ npx ness deploy --domain demo.mydomain.com --dir dist --spa

Please provide your AWS credentials
Where can I find these?

🔑 AWS_ACCESS_KEY_ID:
🤐 AWS_SECRET_ACCESS_KEY:
```

After trying to find credentials when it prompts me for the credentials, I put in my valid access & secret keys, but it's still prompting me the same info over and over again. 

I've tested this with Node v12 & v14

**Comment by adamelmore** [comment]
Hi @rushi! Thanks for trying out Ness. Can you tell me which OS you're running this on?

**Comment by wuwuwu** [comment]
Same here. MacOs Big Sur 11.4

**Comment by laurasac** [comment]
Same problem. Ubuntu 20.10

**Comment by adamelmore** [comment]
@rushi @wuwuwu @laurasac any of you mind to tell me how you install Node? Standalone installer? NVM? Something else?

**Comment by wuwuwu** [comment]
Nvm indeed

**Comment by laurasac** [comment]
with apt install

**Comment by rezaep** [comment]
Same here. 
OS: Manjaro 21.0.7
Installation type: pacman -S npm

**Comment by rushi** [comment]
> @rushi @wuwuwu @laurasac any of you mind to tell me how you install Node? Standalone installer? NVM? Something else?

I use `nvm` to install my node

**Comment by adamelmore** [comment]
I'm still looking into this. If I can't reproduce I may just rework the credentials lookup as this seems fairly widespread.

**Comment by adamelmore** [comment]
@rushi @wuwuwu @laurasac I believe this issue is fixed now. I name the CloudFormation stack with an ID that includes the git branch name of the repository, but I didn't realize that the tool I was using to grab the git branch throws when used in a non-git directory.
