### ISSUE TITLE
"x" emoji is misleading when destroying a site

### ISSUE THREAD

**Issue by eladb** [nessjs/ness#25]
When using `ness destroy`, the output looks like this:

![Screen Shot 2020-12-14 at 12 40 26](https://user-images.githubusercontent.com/598796/102071772-9e83d600-3e09-11eb-844c-6548ebd29f25.png)

The ❌  emoji sends a signal as if the site destruction failed, but it seems like it succeeded (exit code 0 and no errors).

**Comment by adamelmore** [comment]
Yeah, that emoji means something went wrong 😅. The real issue here is that it exited with 0 (and without listing any errors). Will look into this!

**Comment by adamelmore** [comment]
This should be fixed with #37.
