### ISSUE TITLE
vue-cli s3 deploy only includes index file

### ISSUE THREAD

**Issue by lsbyerley** [nessjs/ness#31]
Tried using this to deploy a vue js project generated with the vue cli and only the favicon file and index.html file appears in the s3 bucket. The command to build the project is `vue-cli-service build`

edit: ran the command `npx ness deploy`

**Comment by adamelmore** [comment]
Is there a repo you could share with me?

**Comment by adamelmore** [comment]
It looks like the [default destination directory](https://cli.vuejs.org/guide/cli-service.html#vue-cli-service-build) is `dist`, so you'll need to pass `--dir dist` to ness, like `npx ness deploy --dir dist`. Were you already doing so?

**Comment by lsbyerley** [comment]
@adamelmore hey thanks for the reply, yeah you are right, i did not specify the `--dir dist` flag when i deployed. Looks good so far, will continue to play around with it!
