### ISSUE TITLE
Invalid hook call on npx ness deploy for minimal gatsby starter

### ISSUE THREAD

**Issue by warwickgrigg** [nessjs/ness#93]
First I tried "npx ness deploy" for a minimal index.html file in the public directory. I got the invalid hook call error.

So I followed the instructions in Ness' readme for the clean starter gatsby site.  I got the same invalid hook call error:

  ERROR  Invalid hook call. Hooks can only be called inside of the body of a function component. ...
...
- App (/home/  ........ /node_modules/ness/lib/components/App.js:28:43)
....

I'm using an aws profile for eu-west-2 with permissions that work for a similar aws deployment using Architect (arc.codes). 

I would love to get ness working - a fabulous concept - thank you!

**Comment by adamelmore** [comment]
Will take a look at this tomorrow! Apologies for the delay, I've been head down adding proper Next.js support.

**Comment by adamelmore** [comment]
@warwickgrigg could you provide more info on your environment? (OS and Node versions would be most helpful!)

**Comment by adamelmore** [comment]
@warwickgrigg I also pushed a new release out this morning that fixes some Node compatibility issues. If you get a chance to re-test, I'd be curious if your issue went away!

**Comment by adamelmore** [comment]
@warwickgrigg just checking in! Would love to know whether this is still an issue for you with the latest release of Ness!

**Comment by warwickgrigg** [comment]
I get "AccessDenied ... not authorized to perform: cloudformation:DescribeStackEvents". Do you have a spec of the permissions Ness needs to deploy? I'd rather not give full admin permissions.

**Comment by adamelmore** [comment]
> I get "AccessDenied ... not authorized to perform: cloudformation:DescribeStackEvents". Do you have a spec of the permissions Ness needs to deploy? I'd rather not give full admin permissions.

I'll get this documented!

**Comment by warwickgrigg** [comment]
I've started using aws-vault with MFA to secure admin credentials I'm using for deployments and it's working well for me.  This solves the problem for me: I'm able to deploy it successfully with ness. Thank you for your work on ness!

**Comment by adamelmore** [comment]
Adding some documentation around IAM perms needed is still on my list, but I'm glad you have a workaround!
